/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vectorescreados;


public class MainGui extends javax.swing.JFrame {

    /**
     * Creates new form MainGui
     */
    public Vector Fernando;
    public MainGui() {
        initComponents();
        ElementoUser.setVisible(false);
        PosicionElemento.setVisible(false);
        Aceptar.setVisible(false);
        Saltar.setVisible(false);    
        Fernando = new Vector(100);
        GraficarVector.setVisible(false);
        PosicionesVacias.setVisible(false);
        Retroceder.setVisible(false);
        Posicion.setVisible(false);
        Ingresar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        IntercambiarPosiciones = new javax.swing.JButton();
        CambiarIndice = new javax.swing.JButton();
        Indice1 = new javax.swing.JTextField();
        Indice2 = new javax.swing.JTextField();
        BotonInvertir = new javax.swing.JButton();
        IndiceCambio = new javax.swing.JTextField();
        NumeroCambio = new javax.swing.JTextField();
        TamañoVector = new javax.swing.JTextField();
        Aleatorio = new javax.swing.JButton();
        Manual = new javax.swing.JButton();
        PosicionElemento = new javax.swing.JLabel();
        Aceptar = new javax.swing.JButton();
        Saltar = new javax.swing.JButton();
        ElementoUser = new javax.swing.JTextField();
        PosicionesVacias = new javax.swing.JLabel();
        GraficarVector = new javax.swing.JButton();
        Retroceder = new javax.swing.JButton();
        CambiarIndiceAleatoriamente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        VectorMostrado = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Posicion = new javax.swing.JLabel();
        Ingresar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        IntercambiarPosiciones.setText("Intercambiar Posiciones");
        IntercambiarPosiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntercambiarPosicionesActionPerformed(evt);
            }
        });

        CambiarIndice.setText("Cambiar Indice");
        CambiarIndice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarIndiceActionPerformed(evt);
            }
        });

        Indice1.setText("1");

        Indice2.setText("2");

        BotonInvertir.setText("Invertir Vector");
        BotonInvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInvertirActionPerformed(evt);
            }
        });

        IndiceCambio.setText("1");

        NumeroCambio.setText("0");

        Aleatorio.setText("Aleatorio");
        Aleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AleatorioActionPerformed(evt);
            }
        });

        Manual.setText("Manual");
        Manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManualActionPerformed(evt);
            }
        });

        PosicionElemento.setBackground(new java.awt.Color(255, 255, 255));
        PosicionElemento.setText("1");
        PosicionElemento.setOpaque(true);

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Saltar.setText("Siguiente");
        Saltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaltarActionPerformed(evt);
            }
        });

        ElementoUser.setText("0");
        ElementoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElementoUserActionPerformed(evt);
            }
        });

        GraficarVector.setText("Graficar Vector");
        GraficarVector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraficarVectorActionPerformed(evt);
            }
        });

        Retroceder.setText("Anterior");
        Retroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetrocederActionPerformed(evt);
            }
        });

        CambiarIndiceAleatoriamente.setText("Cambiar Indice Aleatoriamente");
        CambiarIndiceAleatoriamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarIndiceAleatoriamenteActionPerformed(evt);
            }
        });

        VectorMostrado.setColumns(20);
        VectorMostrado.setRows(5);
        jScrollPane2.setViewportView(VectorMostrado);

        jLabel2.setText("Indice");

        jLabel3.setText("Numero a cambiar");

        jLabel4.setText("Indice 1");

        jLabel5.setText("Indice 2");

        jLabel6.setText("Tamaño del Vector a crear");

        jLabel7.setText("Vector creado");

        Posicion.setText("Posicion actual");

        Ingresar.setText("Numero a ingresar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CambiarIndiceAleatoriamente)
                            .addComponent(CambiarIndice)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(NumeroCambio, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IndiceCambio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IntercambiarPosiciones)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Indice2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Indice1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)))
                        .addGap(65, 65, 65)
                        .addComponent(BotonInvertir)
                        .addGap(189, 189, 189))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(TamañoVector, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(Aleatorio)
                                            .addGap(33, 33, 33)
                                            .addComponent(Manual))
                                        .addComponent(jScrollPane2))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ElementoUser)
                                    .addComponent(Aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PosicionElemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Saltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Retroceder, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(Posicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GraficarVector)
                            .addComponent(PosicionesVacias, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Posicion)
                    .addComponent(Ingresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ElementoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PosicionElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(Saltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(GraficarVector, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Retroceder, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PosicionesVacias, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TamañoVector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Aleatorio)
                                    .addComponent(Manual))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IndiceCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumeroCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(CambiarIndice)
                        .addGap(10, 10, 10)
                        .addComponent(CambiarIndiceAleatoriamente))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Indice1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Indice2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IntercambiarPosiciones)
                            .addComponent(BotonInvertir))))
                .addGap(23, 23, 23))
        );

        Aceptar.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AleatorioActionPerformed
    /*Este Boton crea un Vector del tamaño ingresado y lo llena con numeros
    Aleatorios, ademas de ocultar los botones para llenar el Vector manualmente
    Si estos se activaron antes*/    
        int numeroUsuario = Integer.parseInt(this.TamañoVector.getText());
        this.VectorMostrado.setText(Fernando.LlenarVector(numeroUsuario));
        ElementoUser.setVisible(false);
        PosicionElemento.setVisible(false);
        Aceptar.setVisible(false);
        Saltar.setVisible(false);
        Retroceder.setVisible(false);
        PosicionesVacias.setVisible(false);
        GraficarVector.setVisible(false);
        PosicionElemento.setText(Integer.toString(1));
        ElementoUser.setText("");
        
    }//GEN-LAST:event_AleatorioActionPerformed

    private void ManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManualActionPerformed
    /*Este boton activa la interfaz para llenar el vector del tamaño ingresado*/    
        ElementoUser.setVisible(true);
        PosicionElemento.setVisible(true);
        Aceptar.setVisible(true);
        Saltar.setVisible(true);
        Retroceder.setVisible(true);
        VectorMostrado.setText("");
        PosicionElemento.setText(Integer.toString(1));
        Posicion.setVisible(true);
        Ingresar.setVisible(true);
    }//GEN-LAST:event_ManualActionPerformed

    private void ElementoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElementoUserActionPerformed
        //Este es codigo basura, no se como borrarlo
    }//GEN-LAST:event_ElementoUserActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
    /*Este boton llena el vector en la posicion actual con el numero a ingresar
    y pasa a la posicion siguiente hasta que se llega a la situacion donde el
    tamaño del vector es igual a la posicion actual, lo que hace visible el boton
    de graficar y el anuncia al Usuario si hay alguna una posicion nula, y si la 
    hay se completa con un cero*/
        int Numero = Integer.parseInt(ElementoUser.getText());            
        int cambio = Integer.parseInt(PosicionElemento.getText());
        if (Integer.parseInt(PosicionElemento.getText())== Integer.parseInt(this.TamañoVector.getText()))
        {
           String mensaje = "" ;
           GraficarVector.setVisible(true);
           PosicionElemento.setText(Integer.toString(cambio));
           for(int i = 1; i < cambio+1; ++i)
            {
                if (Fernando.arreglo[i-1] == 0 && Integer.parseInt(PosicionElemento.getText()) == 1+Integer.parseInt(this.TamañoVector.getText()))
                {
                    PosicionesVacias.setVisible(true);
                    mensaje = mensaje + i + ",";
                }                
                PosicionesVacias.setText("Las posiciones " +mensaje + " No estan llenadas y se completaran con ceros");
            }
           
        }
        if (Integer.parseInt(PosicionElemento.getText()) < 1+Integer.parseInt(this.TamañoVector.getText()))          
        {
            Fernando.arreglo[cambio-1] = Numero;
            cambio = cambio + 1;
            PosicionElemento.setText(Integer.toString(cambio));
        } 
        if (Integer.parseInt(PosicionElemento.getText()) == 1+Integer.parseInt(this.TamañoVector.getText()))
        {
           PosicionElemento.setText(Integer.toString(Integer.parseInt(this.TamañoVector.getText())));
        }
    }//GEN-LAST:event_AceptarActionPerformed

    private void SaltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaltarActionPerformed
    /*Este boton avanza la posicion actual por una posicion y si se llega a la 
    situacion donde el tamaño del vector es igual a la posicion actual, lo que 
    hace visible el boton de graficar y el anuncia al Usuario si hay alguna una
    posicion nula, y si la hay se completa con un cero**/   
        int cambio = Integer.parseInt(PosicionElemento.getText());
        if (Integer.parseInt(PosicionElemento.getText()) < 1+Integer.parseInt(this.TamañoVector.getText()))
        {
            cambio = cambio + 1;
        }       
        PosicionElemento.setText(Integer.toString(cambio)); 
        if (Integer.parseInt(PosicionElemento.getText()) == 1+Integer.parseInt(this.TamañoVector.getText()))
        {           
           String mensaje = "" ;
           GraficarVector.setVisible(true);
           cambio = cambio - 1;
           PosicionElemento.setText(Integer.toString(cambio));
           for(int i = 1; i < cambio+1; ++i)
            {
                if (Fernando.arreglo[i-1] == 0)
                {
                    PosicionesVacias.setVisible(true);
                    mensaje = mensaje + i + ",";
                }
            }
           PosicionesVacias.setText("Las posiciones " +mensaje + " No estan llenadas y se completaran con ceros");
        }     
    }//GEN-LAST:event_SaltarActionPerformed

    private void RetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetrocederActionPerformed
    /*Este boton retrocede la posicion actual por una posicion*/    
        int cambio = Integer.parseInt(PosicionElemento.getText());
        if (cambio > 1)
        {
            cambio = cambio - 1;
        }       
        PosicionElemento.setText(Integer.toString(cambio));
    }//GEN-LAST:event_RetrocederActionPerformed

    private void GraficarVectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraficarVectorActionPerformed
    /*Este boton grafica el vector ingresado manualmente y oculta los botones
    y elementos usados para crearlo*/        
        int X = Integer.parseInt(this.TamañoVector.getText()); 
        VectorMostrado.setText(Fernando.Pintar(X+1));
        ElementoUser.setVisible(false);
        PosicionElemento.setVisible(false);
        Aceptar.setVisible(false);
        Saltar.setVisible(false);
        Retroceder.setVisible(false);
        PosicionesVacias.setVisible(false);
        GraficarVector.setVisible(false);
        PosicionElemento.setText(Integer.toString(0));
        ElementoUser.setText("");
        Posicion.setVisible(false);
        Ingresar.setVisible(false);
    }//GEN-LAST:event_GraficarVectorActionPerformed

    private void CambiarIndiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarIndiceActionPerformed
/*Este boton hace uso del metodo cambiar posicion, cogiendo el indice a cambiar,
el numero a cambiar y el tamaño del vector creado, y luego lo imprime con el
cambio realizado*/
this.VectorMostrado.setText(Fernando.CambiarPosicion
        (
        Integer.parseInt(IndiceCambio.getText()), //Indice a cambiar
        Integer.parseInt(NumeroCambio.getText()), //numero a cambiar
        Integer.parseInt(TamañoVector.getText())  //Tamaño del Vector
        )
);
    }//GEN-LAST:event_CambiarIndiceActionPerformed

    private void CambiarIndiceAleatoriamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarIndiceAleatoriamenteActionPerformed
/*Este boton hace uso del metodo cambiar posicion aleatoria,
cogiendo el indice a cambiar y el tamaño del vector creado, y luego lo imprime 
con el cambio realizado*/
this.VectorMostrado.setText(Fernando.CambiarPosicionAleatorio
        (
        Integer.parseInt(IndiceCambio.getText()), //Indice a cambiar
        Integer.parseInt(TamañoVector.getText())  //Tamaño del Vector
        )
);
    }//GEN-LAST:event_CambiarIndiceAleatoriamenteActionPerformed

    private void IntercambiarPosicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntercambiarPosicionesActionPerformed
/*Este boton hace uso del metodo intercambiar posiciones, haciendo que los
dos indices dados por el usuario cambien posiciones entre si*/
this.VectorMostrado.setText(Fernando.CambiarIndices
        (
        Integer.parseInt(Indice1.getText()), //Primer Indice
        Integer.parseInt(Indice2.getText()), //Segundo indice
        Integer.parseInt(TamañoVector.getText()) //Tamaño del Vector
        )               
);
    }//GEN-LAST:event_IntercambiarPosicionesActionPerformed

    private void BotonInvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInvertirActionPerformed
/*Este boton invierte el Vector creado*/
if (!"".equals(VectorMostrado.getText()))
    {
    this.VectorMostrado.setText(Fernando.InvertirVector
    (
        Integer.parseInt(TamañoVector.getText())
    )
); 
    }
    }//GEN-LAST:event_BotonInvertirActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        //este codigo es basura, no se como borrarlo
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Aleatorio;
    private javax.swing.JButton BotonInvertir;
    private javax.swing.JButton CambiarIndice;
    private javax.swing.JButton CambiarIndiceAleatoriamente;
    private javax.swing.JTextField ElementoUser;
    private javax.swing.JButton GraficarVector;
    private javax.swing.JTextField Indice1;
    private javax.swing.JTextField Indice2;
    private javax.swing.JTextField IndiceCambio;
    private javax.swing.JLabel Ingresar;
    private javax.swing.JButton IntercambiarPosiciones;
    public static javax.swing.JButton Manual;
    private javax.swing.JTextField NumeroCambio;
    private javax.swing.JLabel Posicion;
    private javax.swing.JLabel PosicionElemento;
    private javax.swing.JLabel PosicionesVacias;
    private javax.swing.JButton Retroceder;
    private javax.swing.JButton Saltar;
    private javax.swing.JTextField TamañoVector;
    private javax.swing.JTextArea VectorMostrado;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}